title: Learning Git Pages
author: William Murrah
email: william.murrah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test blog site.
theme: minima
# social links
twitter_username: EdStat # DO NOT include the @ character, or else the build will fail!
github_username:  wmmurrah # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
